global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'finance_app'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'system'
    static_configs:
      - targets: ['localhost:9100'] 